name: Build for Github pages

inputs:
  name:
    description: "Artifact name"
    required: false
    default: "abi2023"
  path:
    description: "Path of the directory containing the static assets."
    required: true
    default: "."
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"

on:
  push:
    branches:
      - "master"

  pull_request:
    types:
      - "closed"
    branches:
      - "master"

jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Informatik/informatik.tex

      - name: Create archive
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
        env:
          INPUT_PATH: ${{ inputs.path }}

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}

  deploy:
    runs-on: ubuntu-latest

    needs: build_pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
